general:
  id: 1
  name: IoT Gateway Testing
  allowed_hosts: ['localhost', '127.0.0.1']
  storage_type: sqlite
registry:
  max_devices: 10
  timeout_stale: 120.0
  check_interval: 60.0
message_bus:
  max_queue: 20
  timeout: 1.0
logger:
  dir: logs/testing/
  debug: true
  level: '0'