[pytest]
testpaths = tests
asyncio_mode = auto

postgresql_user = test
postgresql_password = test
postgresql_host = localhost
postgresql_port = 5432
postgresql_dbname = testdb

markers =
    unit:        модульные тесты
    integration: интеграция

addopts =
    -v
    --tb=short

log_cli       = true
log_cli_level = WARNING
log_format    = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_date_format = %H:%M:%S
