enabled: true
client_id: iot-gateway
broker:
  host: 127.0.0.1
  port: 1883
bind:
  address: 0.0.0.0
  port: 0
auth:
  username:
  password:
tls:
  use: false
  insecure: false
  ca_certs:
  certfile:
  keyfile:
  keyfile_password:
version: 4
keepalive: 60
qos: 1
clean_session: true
reconnect_delay: 5
max_reconnect_delay: 300
timeout_reject: 2.0
topics:
  devices:
    base: devices/+
    register: devices/+/register
    status: devices/+/status
    command: devices/+/command
    command_response: devices/+/command/response